### ISSUE TITLE
SDK 24 - android.os.FileUriExposedException

### ISSUE THREAD

**Issue by Mathbl** [spacecowboy/NoNonsense-FilePicker#107]
Hi,

It looks like there's an issue when targeting sdk 24 due to a change in the way file system permissions work on Nougat: https://developer.android.com/about/versions/nougat/android-7.0-changes.html#permfilesys

When I press ok after selecting files (tested on emulator with Android 7.0), it throws 

``` java
FATAL EXCEPTION: main
  Process: com.myapp.android, PID: 10719
  android.os.FileUriExposedException: file:///storage/emulated/0/Download/myfile.png exposed beyond app through ClipData.Item.getUri()
      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
      at android.net.Uri.checkFileUriExposed(Uri.java:2346)
      at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
      at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
      at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
      at android.app.Activity.finish(Activity.java:5188)
      at android.app.Activity.finish(Activity.java:5208)
      at com.nononsenseapps.filepicker.AbstractFilePickerActivity.onFilesPicked(AbstractFilePickerActivity.java:150)
      at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:206)
      at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:161)
      at android.view.View.performClick(View.java:5610)
      at android.view.View$PerformClick.run(View.java:22260)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6077)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

Investigating further, I found that the exception is thrown in the toUri method from AbstractFilePickerFragment: 

``` java
    protected List<Uri> toUri(Iterable<T> files) {
        ArrayList<Uri> uris = new ArrayList<>();
        for (T file : files) {
            uris.add(toUri(file));
        }
        return uris;
    }
```

This post gives a solution: https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en but I'm not sure if implementing this would have other consequences.

**Comment by spacecowboy** [comment]
@Mathbl thanks for the report. I'll have a look

**Comment by spacecowboy** [comment]
I am unable to recreate the exception. Running in a nougat emulator, changing target SDK to 24, and even changing the package name in the sample app. Can you provide more information on how you ran into this?

The changes shouldn't affect the library's functionality because the library is a part of your app and the changes should be specific to inter-app communication.

**Comment by Mathbl** [comment]
Ok, you're right about the fact that the library is part of the app. That went through my mind and I didn't understand why the strict mode policy was thrown. 

I tested the sample app with the same emulator and I don't get the exception, so it must be something i'm doing wrong in my code. Note that I'm extending `com.nononsenseapps.filepicker.FilePickerActivity` and `com.nononsenseapps.filepicker.FilePickerFragment` to provide file/folder thumbnails, maybe it has to do with that. I'm gonna have to investigate and try some things.

Sorry for the false flag!
