### ISSUE TITLE
NullPointerException with 4.0.0-beta1 release

### ISSUE THREAD

**Issue by NightSkyDev** [spacecowboy/NoNonsense-FilePicker#122]
First, a big "thanks!" for your library!  I've tried all the libraries I can find and I really appreciate what your doing.  I'm running in to the "FileUriExposedException" issue on my Android 7 device and found the issue:
FileUriExposedException on Android 7" #115

I see where you posted the "4.0.0-beta1" release as a fix so I'm trying it out, but now I'm getting the following NullPointerException: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	 at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
	 at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
	 at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
	 at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:201)
	 at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:28)
	 at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:312)
	 at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:196)
	 at android.view.View.performClick(View.java:5609)
	 at android.view.View$PerformClick.run(View.java:22259)
	 at android.os.Handler.handleCallback(Handler.java:751)
	 at android.os.Handler.dispatchMessage(Handler.java:95)
	 at android.os.Looper.loop(Looper.java:154)
	 at android.app.ActivityThread.main(ActivityThread.java:6077)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
It's pretty basic, but here's the code I'm using to call the library:

```
Intent intent = new Intent(this, com.nononsenseapps.filepicker.FilePickerActivity.class);
intent.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
intent.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
intent.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
intent.putExtra(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());
startActivityForResult(intent, FILE_CODE);

```
I've called the intent with setting EXTRA_ALLOW_MULTIPLE true and false.  

Thanks!

**Comment by spacecowboy** [comment]
That error is due to nothing being picked yet. But in that case, it should not be possible to click the OK button. What do you do in the interface? Could you give a step by step instruction?

**Comment by NightSkyDev** [comment]
I should have mentioned, this exact same code works fine when using the '3.1.0' version of the library.  All I did was swap the library to use '4.0.0-beta1'.

>Could you give a step by step instruction?

Sure, I called the library using the code I listed above:
1. The dialog opens as it did in version 3.  
2. I clicked on a folder, which opened up to list some files on my device
3. I selected a file and hit OK

As a test, I created a new Android project with a single button that calls the Intent as shown above.  I used the default style and Activity declaration as shown in your README.  I'm getting the same exception on both an Android 5 and Android 7 device.

**Comment by lhassaine** [comment]
In the manifest.xml, make sure you have added both the provider and activity elements within the application element: 

`       
  <application
        ...>
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/nnf_provider_paths"/>
        </provider>

        <activity
            android:name="com.nononsenseapps.filepicker.FilePickerActivity"
            android:label="@string/app_name"
            android:theme="@style/FilePickerTheme">
            <intent-filter>
                <action android:name="android.intent.action.GET_CONTENT" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    ...
    </application`

**Comment by kevindesai777** [comment]
@NightSkyDev any fix on this one? I am having the same issue.

**Comment by NightSkyDev** [comment]
@kevindesai777 I'm not the developer for this library, I just reported the problem.  I stopped using the library when I didn't get a response.

**Comment by spacecowboy** [comment]
@NightSkyDev that's because @lhassaine gave the proper advice but you never responded to that.

@kevindesai777 if you are seeing this then follow @lhassaine 's advice or just follow the steps in the README. And I do mean ALL steps.

**Comment by spacecowboy** [comment]
This change was clearly listed in the changelog: https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/4.0.0

**Comment by NightSkyDev** [comment]
>@NightSkyDev that's because @lhassaine gave the proper advice but you never responded to that.
lhassaine commented 3 months after I posted... I already moved on.  Also, I did set up the File Provider in the manifest.

**Comment by kevindesai777** [comment]
Hey @spacecowboy. I followed all the steps, rechecked it multiple times. I'll give it a try and report back if I can fix it.
