### ISSUE TITLE
Error while importing library module of Version 3.1.0

### ISSUE THREAD

**Issue by jondoes** [spacecowboy/NoNonsense-FilePicker#126]
Hello spacecowboy,

I have import library directory in my project as a module dependencies.
But while doing so I have got below exception.

Error:Exception thrown while executing model rule: PublishingPlugin.Rules#addConfiguredPublicationsToProjectPublicationRegistry(ProjectPublicationRegistry, PublishingExtension, ProjectIdentifier)

is there any solution for this ?
and kindly request to you that please make project downloaded zip directly useable.

First I have download code in zip using clone or download option and import that project, it works good but when I use that library in my other project the above same exception occur.

Then I tried with use in app level gradle.build using dependencies **compile 'com.nononsenseapps:filepicker:3.1.0'**  then it gives below exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.nononsenseapps.filepicker.FilePickerActivity}: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton

by any of ways I can't use version 3.1.0

Thanks.

**Comment by spacecowboy** [comment]
> and kindly request to you that please make project downloaded zip directly useable.

I have no idea what you mean here. That is not how you use android libraries.

> Then I tried with use in app level gradle.build using dependencies compile 'com.nononsenseapps:filepicker:3.1.0'

This is the correct way of doing it.

>  then it gives below exception
>
>java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.nononsenseapps.filepicker.FilePickerActivity}: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton

I'm 90% sure you are running into this problem: https://github.com/spacecowboy/NoNonsense-FilePicker/issues/110

Which is solved in [4.0.0-beta1](https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/4.0.0-beta1). Please try and changing your gradle files accordingly and see if that fixes your problem (*NOTE*: some APIs changed, this might break your code in other ways).

**Comment by jondoes** [comment]
To make downloaded project zip directly usable means that the library folder in the directory of project, If we import that library in our project then it should be work.

But as we need to do git clone to use this project. 
So I think library also contains dynamic values of git inserted in project. thats why it's not directly used in other projects.

Is there any way to clone the library from git in our project ?

Right now I have changed 3.1.0 to 4.0.0 in build.gradle file. 
But still I got below issue.

Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton
Caused by: java.lang.NumberFormatException: Invalid int: "?2130771995"
at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)

Thanks.

**Comment by spacecowboy** [comment]
@jondoes please paste the entire stack trace and I'll assist but that error is not related to this library. You've defined something wrong somewhere, either in a theme file or layout file.

If you want to embed the source directly just use a submodule: https://git-scm.com/docs/git-submodule
Here's a good tutorial as well: https://github.com/blog/2104-working-with-submodules

For example, if you want to place it inside a libraries subfolder, do

```
git submodule add https://github.com/spacecowboy/NoNonsense-FilePicker.git libraries/nononsense-filepicker
git submodule update --init --recursive
```

**Comment by jondoes** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.multiplefilepicker, PID: 6842
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.multiplefilepicker/com.multiplefilepicker.FilePickerActivity2}: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at com.nononsenseapps.filepicker.AbstractFilePickerFragment.inflateRootView(AbstractFilePickerFragment.java:239)
                                                     at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onCreateView(AbstractFilePickerFragment.java:165)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                     at android.app.Activity.performStart(Activity.java:5241)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NumberFormatException: Invalid int: "?2130771973"
                                                     at java.lang.Integer.invalidInt(Integer.java:137)
                                                     at java.lang.Integer.parse(Integer.java:374)
                                                     at java.lang.Integer.parseInt(Integer.java:365)
                                                     at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
                                                     at android.content.res.TypedArray.getInt(TypedArray.java:255)
                                                     at android.widget.ImageView.<init>(ImageView.java:155)
                                                     at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:60)
                                                     at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:56)
                                                     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1021)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1080)
                                                 	at android.support.v4.view.LayoutInflaterCompatHC$Facto
```

**Comment by spacecowboy** [comment]
and what version of android is this?

**Comment by erttyy8821** [comment]
I have the same problem. Finally ,  I set the theme to fix it.

Just try it:
```
<style name="FilePickerTheme" parent="NNF_BaseTheme">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="alertDialogTheme">@style/FilePickerAlertDialogTheme</item>
    </style>

    <style name="FilePickerAlertDialogTheme" parent="Theme.AppCompat.Dialog.Alert">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
```

**Comment by spacecowboy** [comment]
Well that is the first requirement of using the library...

Does this fix your issue as well @jondoes

**Comment by erttyy8821** [comment]
@spacecowboy 
Haha , I know. 
I just try to modify style's parent than get the same problem.
BTW , is it possible to customized the 3 style color programmatically ?

**Comment by spacecowboy** [comment]
@erttyy8821 presumably, you could programmatically override whatever is defined in your styles file (it will still be needed though).

That is not something I can help you with though.
