### ISSUE TITLE
crash InBackground thread

### ISSUE THREAD

**Issue by Flinbor** [spacecowboy/NoNonsense-FilePicker#13]
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:142)
at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:135)
at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 3 more
java.lang.NullPointerException
at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:142)
at com.nononsenseapps.filepicker.FilePickerFragment$2.loadInBackground(FilePickerFragment.java:135)
at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:301)
at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:68)
at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:56)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)

**Comment by spacecowboy** [comment]
Thanks for the report. Will have a look.

**Comment by spacecowboy** [comment]
Should be fixed in 1.2.0
