### ISSUE TITLE
NullPointerException at com.nononsenseapps.filepicker.FilePickerFragment.toUri

### ISSUE THREAD

**Issue by kevindesai777** [spacecowboy/NoNonsense-FilePicker#131]
Error Log

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                        at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:201)
                                                                        at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:28)
                                                                        at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:312)
                                                                        at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:196)
                                                                        at android.view.View.performClick(View.java:5697)
                                                                        at android.widget.TextView.performClick(TextView.java:10814)
                                                                        at android.view.View$PerformClick.run(View.java:22526)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

It is happening in this method,

```
public
 @Nullable
    T getFirstCheckedItem() {
        //noinspection LoopStatementThatDoesntLoop
        for (T file : mCheckedItems) {
            return file;
        }
        return null;
    }
```

It's returning null instead of returning my file. I am just selecting a single file and clicking okay. 
Testing on a Samsung Galaxy S7 with Android 6.0

**Comment by spacecowboy** [comment]
The function is very clear. It can return null (see the `@Nullable` annotation) and you need to handle that possibility accordingly in your app.

Now why the checked items list is empty is a different question though and I can't answer that without more information.

**Comment by kevindesai777** [comment]
Thanks for the prompt reply. 
mCheckedItems is not null. So it should return the file.
Since it is returning a null,         
`mListener.onFilePicked(toUri(getFirstCheckedItem()));
` is causing the null pointer exception. 
It is exactly the same as issue #122

**Comment by spacecowboy** [comment]
It's not null but it is empty, so there is nothing to return

Den 30 mars 2017 00:06 skrev "Kevin Desai" <notifications@github.com>:

**Comment by sakshiigoyal** [comment]
having same problem.
