### ISSUE TITLE
Seleted files get deselected when application goes in background.

### ISSUE THREAD

**Issue by ashwini-pandarkat1993** [spacecowboy/NoNonsense-FilePicker#135]
I am having one Activity which Extends **FilePickerActivity** and in FilePickerActivity for filtering extensions of file. 
       AbstractFilePickerFragment<File> fragment = new CustomFilePickerFragment();
```
 public static class CustomFilePickerFragment extends FilePickerFragment {

        // File extension to filter on
        private static final String[] EXTENSIONS = new String[] { ".txt", ".pdf", ".doc", ".docx",".jpg",".png",".jpeg"};
        private static final String[] EXTENSIONS2 = new String[] { ".jpg",".png",".jpeg"};

        /**
         *
         * @param file
         * @return The file extension. If file has no extension, it returns
         *         null.
         */
        private String getExtension(@NonNull File file) {
            String path = file.getPath();
            int i = path.lastIndexOf(".");
            if (i < 0) {
                return null;
            } else {
                return path.substring(i);
            }
        }

        @Override
        protected boolean isItemVisible(final File file) {
            boolean ret = super.isItemVisible(file);
            if (ret && !isDir(file) && (mode == MODE_FILE || mode == MODE_FILE_AND_DIR)) {
                String ext = getExtension(file);
                if(from != null && from.equals("ads")) {
                    return ext != null && Arrays.asList(EXTENSIONS2).contains(ext);
                } else {
                    return ext != null && Arrays.asList(EXTENSIONS).contains(ext);
                }

            }
            return ret;
        }

    }
 
```
Here I am selecting multiple files.
But when I select files and send application into background then all selected files get deselected.

**Comment by spacecowboy** [comment]
Thanks for the report. I can recreate it in the sample app as well. I'll investigate

**Comment by ashwini-pandarkat1993** [comment]
Updated library with latest code but after click on OK button application crash Following are logs:

04-10 11:40:25.077 26388-26388/service.com.m2 E/AndroidRuntime: FATAL EXCEPTION: main
Process: service.com.m2, PID: 26388
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:201)
at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:28)
at com.nononsenseapps.filepicker.AbstractFilePickerFragment.toUri(AbstractFilePickerFragment.java:360)
at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:309)
at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:196)
at android.view.View.performClick(View.java:4780)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by spacecowboy** [comment]
@ashwini-pandarkat1993 that's a duplicate of https://github.com/spacecowboy/NoNonsense-FilePicker/issues/136 , please follow instructions there.

This project follows [Semantic Versioning](http://semver.org/). Please always read the changelog before upgrading between major versions (from 3.x.x to 4.x.x for example)
