### ISSUE TITLE
Version 4.0.0 crashes NullPointer Exception

### ISSUE THREAD

**Issue by fmeneuhe** [spacecowboy/NoNonsense-FilePicker#136]
After selecting a folder, I get this crash in Android 4.2:

 FATAL EXCEPTION: main
                                                                                    java.lang.NullPointerException
                                                                                        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                                                        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                                                        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                                                        at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:201)
                                                                                        at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java:28)
                                                                                        at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:314)
                                                                                        at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:196)
                                                                                        at android.view.View.performClick(View.java:4204)
                                                                                        at android.view.View$PerformClick.run(View.java:17355)
`

**Comment by fmeneuhe** [comment]
I need to do a new app update but I cannot do it with this crash. 
Which is the latest stable release to download?
Thanks

**Comment by spacecowboy** [comment]
See https://github.com/spacecowboy/NoNonsense-FilePicker/releases

**Comment by spacecowboy** [comment]
Looking at where the crash occurs makes me wonder.. Do you have the correct `file-provider` section defined in your manifest? As described here: https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/4.0.0

### Breaking changes
- You are now required to define a `FileProvider` in your manifest for the SD-card picker [101aa70](https://github.com/spacecowboy/NoNonsense-FilePicker/commit/101aa705f563d6a8a220d14cde9439bd89e30ab0)
  
  Due to recent changes in Android 7.0 Nougat, bare File URIs can no longer be returned in a safe way. This change requires you to add an entry to your manifest to use the included `FilePickerFragment` and change how you handle the results.
  - You need to add the following to your app's `AndroidManifest.xml`:
  
  ``` xml
      <provider
          android:name="android.support.v4.content.FileProvider"
          android:authorities="${applicationId}.provider"
          android:exported="false"
          android:grantUriPermissions="true">
          <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/nnf_provider_paths" />
      </provider>
  ```
  - Then you must change your result handling. Here is a code snippet illustrating the change for a single result (the same applies to multiple results):
  
  ``` java
  protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
      // The URI will now be something like content://PACKAGE-NAME/root/path/to/file
      Uri uri = intent.getData();
      // A new utility method is provided to transform the URI to a File object
      File file = com.nononsenseapps.filepicker.Utils.getFileForUri(uri);
      // If you want a URI which matches the old return value, you can do
      Uri fileUri = Uri.fromFile(file);
      // Do something with the result...
  }
  ```
  
  This change was required in order to fix `FileUriExposedException` being thrown on Android 7.0 Nougat, as reported in [#115](https://github.com/spacecowboy/NoNonsense-FilePicker/issues/115) and [#107](https://github.com/spacecowboy/NoNonsense-FilePicker/issues/107).
  
  Please see the updated [activity in the sample app](https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/sample/src/main/java/com/nononsenseapps/filepicker/sample/NoNonsenseFilePicker.java) for more examples.

**Comment by spacecowboy** [comment]
Reason I suspect this is because your crash log indicates that the NPE occurs at line 583 in `FileProvider.java` which is the third line here:

```
        final ProviderInfo info = context.getPackageManager()
                .resolveContentProvider(authority, PackageManager.GET_META_DATA);
        final XmlResourceParser in = info.loadXmlMetaData(
                context.getPackageManager(), META_DATA_FILE_PROVIDER_PATHS);
```

so `info` is null, which it should only be if you don't have a correct `<provider>` section in your manifest.

**Comment by fmeneuhe** [comment]
I did not see the new changes for Android 7 and I did not set up the file profider in manifest.xml, I will try to see if that is the reason. 
Thanks.

**Comment by fmeneuhe** [comment]
One question, if the reason was I did not register the provider in manifest.xml, why the crash only happens in Android 4.x? It should also happen in Android 5 and up, no?

**Comment by spacecowboy** [comment]
No, the functionality is the same across all version of Android. Behavior isn't different.

The change was introduced because it became required in Android 7.
