### ISSUE TITLE
Latest version crashes with NPE

### ISSUE THREAD

**Issue by ankitbatra11** [spacecowboy/NoNonsense-FilePicker#141]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java)
       at com.nononsenseapps.filepicker.FilePickerFragment.toUri(FilePickerFragment.java)
       at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk$3c7ec8c3(AbstractFilePickerFragment.java)
       at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java)
       at android.view.View.performClick(View.java:5076)
       at android.view.View$PerformClick.run(View.java:20279)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by khizar-lango** [comment]
Facing same issue

**Comment by spacecowboy** [comment]
@ankitbatra11 @khizar-lango this is not a bug. You have not configured the library correctly. See my response here: https://github.com/spacecowboy/NoNonsense-FilePicker/issues/136#issuecomment-292756797

**Comment by ankitbatra11** [comment]
Thanks. Will take a look and get back if required. Closing it for now...
