### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by VinitYadav** [spacecowboy/NoNonsense-FilePicker#144]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rudiment.saltysoldier/com.nononsenseapps.filepicker.FilePickerActivity}: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class ImageButton
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                          Caused by: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class ImageButton
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                             at com.nononsenseapps.filepicker.AbstractFilePickerFragment.inflateRootView(AbstractFilePickerFragment.java:239)
                                                                             at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onCreateView(AbstractFilePickerFragment.java:165)
                                                                             at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                             at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                             at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                             at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1260)
                                                                             at android.app.Activity.performStart(Activity.java:6261)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                          Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class ImageButton
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423)

**Comment by spacecowboy** [comment]
Can't help you without further details.

But based on experience you are most likely using an incorrect theme.

**Comment by andkishor** [comment]
I am facing the same issue.anyone have update on this?

**Comment by spacecowboy** [comment]
@andkishor here's a simple test: can you run the sample app without errors?

If the answer is yes, then you have done something wrong in you configuration. Typically, using the wrong theme results in the error above.

If the answer is no, then there is a bug and I will be able to help you. In that case, be specific about what version of android etc you are seeing the error with.

**Comment by andkishor** [comment]
I am not able to run sample app, getting **connection time out issue**.
What i have done is ,create a one sample app inside that app i have follow all the instruction that you mention and created one button from which i calling the FilePickerActivity with intent,but whenever i click on button it will shows above error **"Caused by: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class ImageButton"**.
I have selected my App theme, and and i am running 7.1.1  version with OnePlus 5 device

**Comment by spacecowboy** [comment]
If you can get an error by running this: https://github.com/spacecowboy/NoNonsense-FilePicker/tree/master/sample

and provide a stack trace that would be most helpful. I have no idea what a `connection time out issue` means.
