### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by Bryanalmo** [spacecowboy/NoNonsense-FilePicker#168]

**Comment by spacecowboy** [comment]
That doesn't sound like it should be a problem. You can have as many providers as you want as long as they all use a unique authority. The filepicker should be defined with

```xml
    <provider
        android:name="androidx.core.content.FileProvider"
        android:authorities="${applicationId}.filepicker_provider"
        android:exported="false"
        android:grantUriPermissions="true">
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/nnf_provider_paths" />
    </provider>
```

note the `filepicker_provider` suffix in the authority. As long as your camera provider doesn't end with that, then you're fine here.

If you post the error log here I might be able to help you further. Giving a link to your manifest file would also help.

**Comment by Bryanalmo** [comment]
Hi! Thanks for the answer.

I tried to add another provider as you said but it always show an error in the execution: 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugManifest'.

This is how I have the Manifest with the two providers, I don't know if I'm doing something wrong

![image](https://user-images.githubusercontent.com/40524653/51325288-9a42b880-1a3a-11e9-8ded-a4fb5e34528f.png)

**Comment by Bryanalmo** [comment]
Hi again, I think I fixed the problem with the providers creating a new empty class that extends from FileProvider, but it doesn't seem to fix the initial error

When I pick a file It shows this error:

2019-01-17 10:09:02.181 22441-22441/android.primer.bryanalvarez.captura_info_gt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: android.primer.bryanalvarez.captura_info_gt, PID: 22441
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://android.primer.bryanalvarez.captura_info_gt.provider/external_files/Download/Descarga-Componente-User28-04-01-2019 22_03_37.xlsx }} to activity {android.primer.bryanalvarez.captura_info_gt/android.primer.bryanalvarez.captura_info_gt.Activities.ActualizarActivity}: java.lang.IllegalArgumentException: Can't decode paths to 'external_files', only for 'root' paths.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalArgumentException: Can't decode paths to 'external_files', only for 'root' paths.
        at com.nononsenseapps.filepicker.Utils.getFileForUri(Utils.java:79)
        at android.primer.bryanalvarez.captura_info_gt.Activities.ActualizarActivity.onActivityResult(ActualizarActivity.java:224)
        at android.app.Activity.dispatchActivityResult(Activity.java:7556)

It says that the error ocurred in this part of my code, but I don't really know why

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == PICK_FILE_REQUEST && resultCode == RESULT_OK) {
            /*File file = new File(data.getData().getPath());
            String path = "/storage/Download/"+data.getData().getLastPathSegment();
            uploadFile(path);*/
            List<Uri> files = Utils.getSelectedFilesFromResult(data);
            for (Uri uri: files) {
                **File file = Utils.getFileForUri(uri);**
                Toast.makeText(this, ""+file.getPath(), Toast.LENGTH_SHORT).show();
            }
        }
    }

I'll really appreciate your help

**Comment by spacecowboy** [comment]
(went ahead and formatted your message with code blocks to make it easier to read)

Well the error being thrown comes from here:
https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/java/com/nononsenseapps/filepicker/Utils.java#L78

And it indicates that you are not invoking the picker correctly. Your `nnf_provider_paths` file seems to be incorrect (or you are making some other kind of error with the path), as indicated by the comment to the function:

```
    /**
     * Convert a uri generated by a fileprovider, like content://AUTHORITY/ROOT/actual/path
     * to a file pointing to file:///actual/path
     *
     * Note that it only works for paths generated with `ROOT` as the path element. This is done if
     * nnf_provider_paths.xml is used to define the file provider in the manifest.
     *
     * @param uri generated from a file provider
     * @return Corresponding {@link File} object
     */
```

As you can see in the default https://github.com/spacecowboy/NoNonsense-FilePicker/blob/master/library/src/main/res/xml/nnf_provider_paths.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <root-path
        name="root"
        path="." />
</paths>
```

the path specified to the provider is named `root`, and that is necessary for that Utils function to work.

Regarding your manifest, your screenshot only shows a single provider, but it only shows a small part of the file. Copy paste the entire file if you want me to look at it.

**Comment by Bryanalmo** [comment]
Hi!, As you asked this is the code from my Manifest:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="android.primer.bryanalvarez.captura_info_gt">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:name=".Initializer"
        android:allowBackup="true"
        android:icon="@mipmap/ic_logo_ezgo"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_logo_ezgo"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
        <provider
            android:name=".MyFileProvider"
            android:authorities="${applicationId}.filepicker_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/nnf_provider_paths" />
        </provider>

        <activity
            android:name=".Activities.MainActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Splash.SplashActivity"
            android:theme="@style/SplashScreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".Activities.LoginActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.VehiculosActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.CotizarActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.MenuActivity"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".Activities.MaquinasActivity"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".Activities.CotizarMaquinaActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.CotizacionesMaquinariaActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.VerCotizacionActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.ActualizarActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.CrearActualizarMaquinaActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.ModificarFiltroActivity"
            android:theme="@style/Others" />
        <activity
            android:name="com.nononsenseapps.filepicker.FilePickerActivity"
            android:label="@string/app_name"
            android:theme="@style/FilePickerTheme">
            <intent-filter>
                <action android:name="android.intent.action.GET_CONTENT" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <activity
            android:name=".Activities.CotizarRepuestosActivity"
            android:theme="@style/Others" />
        <activity
            android:name=".Activities.CotizacionesRepuestosActivity"
            android:theme="@style/Others" />
        <activity android:name=".Activities.CrearActualizarVehiculoActivity"
            android:theme="@style/Others"></activity>
    </application>

</manifest>


About my nnf_provider_paths I have exactly the same that in the example, I just add an <external-path> to  try to fix it but It didn't work, this is my nnf_provider_paths file:

<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <root-path name="root" path="." />
    <external-path name="external_files" path="."/>
</paths>

**Comment by spacecowboy** [comment]
Well there's your error. Your `nnf_provider_paths` file contains

```xml
<external-path name="external_files" path="."/>
```

and that's why the Utils function crashes. Just remove it. I'm 80% certain you don't need it (external files are mounted as a subdirectory under root).

Your manifest looks OK. Your providers are using unique authorities so that should work fine. Btw you list `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` twice.

**Comment by Bryanalmo** [comment]
Hi, sorry for the late answer

I deleted the external path tag just like you said and the error is still there. Actually before I post the code above I added that tag in order to try to fix the error and It doesn't seem to change anything

**Comment by spacecowboy** [comment]
Well you're getting a result back. Just look at what the utils function is doing and copy it. You can add suitable debug prints to it.
