### ISSUE TITLE
 java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by gmptr5797** [spacecowboy/NoNonsense-FilePicker#169]
Getting file not found exception after selecting the file. 

**Below is the code snipped used,**
**To Open the FilePicker** 
```
 Intent i = new Intent(getActivity(), FilePickerActivity.class);
                        i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
                        i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, false);
                        i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_FILE);
                        i.putExtra(FilePickerActivity.EXTRA_START_PATH, Environment.getExternalStorageDirectory().getPath());
                        startActivityForResult(i, FILE_CODE); 
```

**To Get the Data** 

```
Uri  picUri=data.getData();
String filename=picUri.toString().substring(fileConvert.indexOf("/")).replaceAll("\\%20"," ");
File f=new File(filename);
InputStream  inputStream = new FileInputStream(f.getAbsolutePath());
```

**Getting the error as**
```
`05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err: java.io.FileNotFoundException: /com.test.apps.provider/root/storage/emulated/0/DCIM/Camera/20190531_095912.jpg: open failed: ENOENT (No such file or directory)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at com.test.apps .Fragments.UploadRecord.onActivityResult(UploadRecord.java:337)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7165)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4994)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5041)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.ActivityThread.-wrap24(ActivityThread.java)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7325)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
05-31 12:38:18.848 23124-23124/com.test.apps  W/System.err:     at libcore.io.Posix.open(Native Method)
05-31 12:38:18.858 23124-23124/com.test.apps  W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
05-31 12:38:18.858 23124-23124/com.test.apps  W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
05-31 12:38:18.858 23124-23124/com.test.apps  W/System.err: 	... 15 more`
```

**Android Gradle Details** 
` minSdkVersion 21
 targetSdkVersion 28
versionCode 17
compileSdkVersion 28
buildToolsVersion '28.0.3' `

Please help me to resolve this issue,

**Comment by spacecowboy** [comment]
You are decoding the URI incorrect. See readme for how to handle the result: https://github.com/spacecowboy/NoNonsense-FilePicker#handling-the-result

But you shouldn't even be using this library because your minimum version of Android is newer than Kitkat. You should use the built-in Storage Access Framework: https://developer.android.com/guide/topics/providers/document-provider
