### ISSUE TITLE
ClassCastException warning

### ISSUE THREAD

**Issue by aryarohit07** [spacecowboy/NoNonsense-FilePicker#26]
Key nononsense.intent.START_PATH expected String but value was a java.io.File.  The default value <null> was returned.
Attempt to cast generated internal exception:

java.lang.ClassCastException: java.io.File cannot be cast to java.lang.String
            at android.os.BaseBundle.getString(BaseBundle.java:921)
            at android.content.Intent.getStringExtra(Intent.java:4822)
            at com.nononsenseapps.filepicker.AbstractFilePickerActivity.onCreate(AbstractFilePickerActivity.java:91)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by spacecowboy** [comment]
This is not a bug. You are trying to give a `File` as the intent argument which is not possible. Do this instead:

    i.putExtra(FilePickerActivity.EXTRA_START_PATH, file.getPath());

**Comment by spacecowboy** [comment]
But I realize my README-example is wrong so fixing that...
