### ISSUE TITLE
illegalStateException in my app due to NoNonsense-FilePicker

### ISSUE THREAD

**Issue by venkat20390** [spacecowboy/NoNonsense-FilePicker#78]
Hi,

Thanks for writing this library to easy our file picking needs in Android. I really like the library and it is pretty neat and simple compared to other similar libraries. But, i am getting crash report in my bug tracker due to this library. The trace of the crash is 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miragestack.secret.voice.recorder/com.nononsenseapps.filepicker.FilePickerActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplV7.m(SourceFile:3310)
	at android.support.v7.app.AppCompatDelegateImplV7.a(SourceFile:253)
	at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:109)
	at com.nononsenseapps.filepicker.AbstractFilePickerActivity.onCreate(SourceFile:77)
	at android.app.Activity.performCreate(Activity.java:5264)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
	... 11 more

Can you help me out to fix this issue? 

Regards,
Venkat.

**Comment by eku** [comment]
RTFM

**Comment by spacecowboy** [comment]
Seems like you have defined an incorrect theme:

```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

Make sure you define the correct theme (which inherits from `NNF_BaseTheme`) in your manifest, as stated here https://github.com/spacecowboy/NoNonsense-FilePicker#configure-the-theme and here https://github.com/spacecowboy/NoNonsense-FilePicker#include-the-file-picker-activity

**Comment by spacecowboy** [comment]
@venkat20390 did you manage to fix your issue?
