### ISSUE TITLE
A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by Lakshmipathi** [spacecowboy/NoNonsense-FilePicker#80]
I'm using your below sample code, with Android-5.0 It crashes with " A TaskDescription's primary color should be opaque". It works well on KitKat. If this error is not related to  NoNonsense-FilePicker, Please close the issue as invalid, sorry for the noise :)

```
public static final int MODE_FILE = AbstractFilePickerFragment.MODE_FILE;
    public static final int MODE_FILE_AND_DIR =
            AbstractFilePickerFragment.MODE_FILE_AND_DIR;
    public static final int MODE_DIR = AbstractFilePickerFragment.MODE_DIR;

    @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    @Override

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        //if (requestCode == FILE_CODE && resultCode == Activity.RESULT_OK) {
        Uri uri = null;
        if (requestCode == 1 && resultCode == Activity.RESULT_OK) {
            if (data.getBooleanExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false)) {
                // For JellyBean and above
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                    ClipData clip = data.getClipData();

                    if (clip != null) {
                        for (int i = 0; i < clip.getItemCount(); i++) {
                             uri = clip.getItemAt(i).getUri();
                            // Do something with the URI
                        }
                    }
                    // For Ice Cream Sandwich
                } else {
                    ArrayList<String> paths = data.getStringArrayListExtra
                            (FilePickerActivity.EXTRA_PATHS);

                    if (paths != null) {
                        for (String path: paths) {
                             uri = Uri.parse(path);
                            // Do something with the URI

                        }
                    }
                }

            } else {
                 uri = data.getData();
                // Do something with the URI      }
        }

    }



    public void picker() {


        Intent i = new Intent(this, FilePickerActivity.class);

        i.putExtra(FilePickerActivity.EXTRA_ALLOW_MULTIPLE, false);
        i.putExtra(FilePickerActivity.EXTRA_ALLOW_CREATE_DIR, true);
        i.putExtra(FilePickerActivity.EXTRA_MODE, FilePickerActivity.MODE_DIR);

        i.putExtra(FilePickerActivity.EXTRA_START_PATH, "/");
        startActivityForResult(i, MODE_DIR);
    }
```
stracetrace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.nononsenseapps.filepicker.FilePickerActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2366)
	at android.app.ActivityThread.access$800(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
	at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:540)
	at android.app.Activity.onApplyThemeResource(Activity.java:3764)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:141)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:86)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2252)
```

**Comment by spacecowboy** [comment]
Hmm. This seems to be an issue with the theme. The error suggests that you (or I?) have included an alpha-channel.

What is the `primaryColor` defined to be in your file-picker theme?

**Comment by Lakshmipathi** [comment]
Here's the style.xml for FilePicker: 
```
  <!-- file chooser -->
    <!-- You can also inherit from NNF_BaseTheme.Light -->
    <style name="FilePickerTheme" parent="NNF_BaseTheme">
        <!-- Set these to match your theme -->
        <item name="colorPrimary">@color/lighter</item>
        <item name="colorPrimaryDark">@color/dark_red</item>
        <item name="colorAccent">@color/default_blue_light</item>

        <!-- Need to set this also to style create folder dialog -->
        <item name="alertDialogTheme">@style/FilePickerAlertDialogTheme</item>

        <!-- If you want to set a specific toolbar theme, do it here -->
        <!-- <item name="nnf_toolbarTheme">@style/ThemeOverlay.AppCompat.Dark.ActionBar</item> -->
    </style>

    <style name="FilePickerAlertDialogTheme" parent="Theme.AppCompat.Dialog.Alert">
        <item name="colorPrimary">@color/lighter</item>
        <item name="colorPrimaryDark">@color/dark_red</item>
        <item name="colorAccent">@color/default_blue_light</item>
    </style>

```
But style.xml(v11) and style.xm(v14) has no FilePickerTheme or FilePickerAlertDialogTheme entries  - may be that the issue?.  From colors.xml 

`    <color name="lighter">#33f7f307</color>
`

**Comment by spacecowboy** [comment]
Your color is the problem. It to

```xml
<color name="lighter">#f7f307</color> 
```

The leading *33* is an alpha channel, making the color slighty transparent, which the error message clearly says is not allowed, which was news to me btw.

**Comment by Lakshmipathi** [comment]
Thanks for the solution, I'll change the color to _#f7f307_

**Comment by spacecowboy** [comment]
NP. Happy you find the library useful!

**Comment by Lakshmipathi** [comment]
As part of a partition app (parted4android),  i can select the mount point -directory-  using this library. Thanks for  your project and your efforts :)

**Comment by am9072** [comment]
ell..!! this is the error only because of primary color opaqueness

go to your res-->values-->color.xml
and remove two digits of primary color

watch video for more easiness.
https://youtu.be/pLO9KzxG--k
